#!/bin/bash -e
# Build an upgrader package for CloudBolt from your currently checked-out code.

[[ -z "$CB" ]] && echo "Sorry, your CB env variable is not set. Go set it to point to your CloudBoltSoftware/cloudbolt repo." && exit 1
[[ ! -d $CB ]] && echo "Sorry, your CB env variable is set to '$CB', but that folder doesn't exist." && exit 1

cmd="$CB/cloudbolt_installer/build_up_and_in_packages.sh -d $CB/src/ -c"
echo "Running: ${cmd}"
${cmd}
