#!/bin/bash -e
# Docker commands for CloudBolt local development & building.
# @param help - Command to run, e.g. 'c docker help'.

dockercmd=$1
[[ -z "${dockercmd}" ]] && dockercmd="help"
[[ -z "$CB" ]] && echo "Sorry, your CB env variable is not set. Go set it to point to your CloudBoltSoftware/cloudbolt repo." && exit 1
[[ ! -d $CB ]] && echo "Sorry, your CB env variable is set to '$CB', but that folder doesn't exist." && exit 1

if [[ -f "$CB/appliances/docker/${dockercmd}" ]]; then
  cmd="$CB/appliances/docker/${dockercmd} ${@:2}"
elif [[ -f "$CB/appliances/docker/${dockercmd}.sh" ]]; then
  cmd="$CB/appliances/docker/${dockercmd}.sh ${@:2}"
else
  echo "Sorry, the docker command you specified does not exist at $CB/appliances/docker/${dockercmd}"
  exit 1
fi

echo "Running: ${cmd}"
${cmd}
