#!/bin/bash -e
# Docker commands for CloudBolt local development & building.
# @param <docker_command> - Command to run, e.g. 'c docker help'.

[[ -z "$CB" ]] && echo "Sorry, your CB env variable is not set. Go set it to point to your CloudBoltSoftware/cloudbolt repo." && exit 1
[[ ! -d $CB ]] && echo "Sorry, your CB env variable is set to '$CB', but that folder doesn't exist." && exit 1
if [[ -f "$CB/appliances/docker/$1" ]]; then
  $CB/appliances/docker/$1 ${@:2}
elif [[ -f "$CB/appliances/docker/$1.sh" ]]; then
  $CB/appliances/docker/$1.sh ${@:2}
else
  echo "Sorry, the docker command you specified does not exist at $CB/appliances/docker/$1"
  exit 1
fi
